Web/PokerStrategy.Web/Controllers/ForumReplyController.cs
namespace PokerStrategy.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PokerStrategy.Data.Models;
    using PokerStrategy.Services.Data;
    using PokerStrategy.Web.ViewModels.Forum;

    public class ForumReplyController : Controller
    {
        private readonly IForumThreadService threadService;
        private readonly IForumReplyService replyService;
        private readonly UserManager<ApplicationUser> userManager;

        public ForumReplyController(
            IForumThreadService threadService,
            IForumReplyService replyService,
            UserManager<ApplicationUser> userManager)
        {
            this.threadService = threadService;
            this.replyService = replyService;
            this.userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
            var currentUser = await this.userManager
                .FindByNameAsync(this.User.Identity.Name);

            var thread = this.threadService.GetById(id);

            var model = new ReplyModel
            {
                PostedByName = currentUser.DisplayName,
                PostedByAvatarUrl = currentUser.ImageUrl,
                RepliedOn = DateTime.UtcNow,
                ThreadId = id,
                ThreadTitle = thread.Title,
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ReplyModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.userManager.GetUserId(this.User);

            await this.replyService.AddReply(userId, model.ThreadId, model.Content);

            return this.RedirectToAction("Thread", "ForumThread", new { id = model.ThreadId });
        }

        [HttpGet]
        public ActionResult EditReplyById(int id) // ViewResult type
        {
            var reply = this.replyService.GetById(id);

            var userId = this.userManager.GetUserId(this.User);

            if (!this.replyService.UserIsCreator(userId, id)
                && !this.User.IsInRole("Admin"))
            {
                 return this.Redirect("/Identity/Account/AccessDenied");
            }

            var model = new ReplyModel
            {
                Id = reply.Id,
                InputContent = reply.Content,
                ThreadId = reply.ThreadId,
                ThreadTitle = reply.Thread.Title,
                CurrentUserIsCreator = this.replyService.UserIsCreator(userId, id),
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditReplyById(ReplyModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.replyService.EditAsync(input.Id, input.InputContent);

            return this.RedirectToAction("Thread", "ForumThread", new { area = "", id = input.ThreadId });
        }
    }
}

Web/PokerStrategy.Web/Controllers/ForumThreadController.cs
namespace PokerStrategy.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PokerStrategy.Data.Models;
    using PokerStrategy.Services.Data;
    using PokerStrategy.Web.ViewModels.Forum;

    public class ForumThreadController : Controller
    {
        private readonly IForumThreadService threadService;
        private readonly IForumCategoryService categoryService;
        private readonly IForumReplyService replyService;
        private readonly UserManager<ApplicationUser> userManager;

        public ForumThreadController(
            IForumThreadService threadService,
            IForumCategoryService categoryService,
            IForumReplyService replyService,
            UserManager<ApplicationUser> userManager)
        {
            this.threadService = threadService;
            this.categoryService = categoryService;
            this.replyService = replyService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult Create(int id)
        {
            var category = this.categoryService.GetById(id);

            var model = new ThreadInputModel
            {
                CategoryId = category.Id,
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ThreadInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.userManager.GetUserId(this.User);

            var thread = await this.threadService.CreateNewThread(userId, model.CategoryId, model.Title, model.Content);

            return this.RedirectToAction("Thread", "ForumThread", new { id = thread.Id });
        }

        public IActionResult Thread(int id)
        {
            var thread = this.threadService.GetById(id);

            var currentUserId = this.userManager.GetUserId(this.User);

            var replies = thread.Replies.Select(r => new ReplyModel
            {
                Id = r.Id,
                PostedByName = r.PostedBy.DisplayName,
                PostedByAvatarUrl = r.PostedBy.ImageUrl,
                RepliedOn = r.CreatedOn,
                InputContent = r.Content,
                ThreadId = r.ThreadId,
                CurrentUserIsCreator = this.replyService.UserIsCreator(currentUserId, r.Id),
            });

            var model = new ThreadViewModel
            {
                Id = thread.Id,
                Title = thread.Title,
                PostedByName = thread.PostedBy.UserName,
                PostedByAvatarUrl = thread.PostedBy.ImageUrl,
                CreatedOn = thread.CreatedOn,
                InputContent = thread.Content,
                Replies = replies.OrderByDescending(r => r.RepliedOn),
            };

            return this.View(model);
        }
    }
}

Web/PokerStrategy.Web/Views/ForumThread/Create.cshtml
@model PokerStrategy.Web.ViewModels.Forum.ThreadInputModel
@using Microsoft.AspNetCore.Identity
@inject UserManager<PokerStrategy.Data.Models.ApplicationUser> UserManager
@inject SignInManager<PokerStrategy.Data.Models.ApplicationUser> SignInManager

<h1>@Model.Title</h1>
<h1>New Thread</h1>
<head>
	@{ViewBag.Title = "Create a Thread"; }
	<link rel="stylesheet" type="text/css" href="~/css/site.css" />

	<script src='https://cdn.tiny.cloud/1/t8478o48f5812yo147q590mh37ekrq9u2t25fbhc0aletbq1/tinymce/5/tinymce.min.js' referrerpolicy="origin">
	</script>
	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'a11ychecker advcode casechange formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
			toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
			toolbar_mode: 'floating',
			tinycomments_mode: 'embedded',
			tinycomments_author: 'Author name',
		});
	</script>
</head>


<form asp-action="Create" method="post" id="addThreadForm">
	<div class="form-group">
		<label asp-for="Title"></label>
		<input asp-for="Title" class="form-control" />
		<span asp-validation-for="Title" class="text-danger"></span>
	</div>
	@*<div asp-validation-summary="All" class="text-danger"></div>*@
	<div class="form-group">
		<label asp-for="InputContent">Thread Content</label>
		<textarea asp-for="InputContent" rows="20" class="form-control" placeholder="Write your message here."></textarea>
		@*<span asp-validation-for="InputContent"></span>*@
		<span asp-validation-for="Content" class="text-danger"></span>
	</div>
	<button type="submit" id="registerBtn" class="btn btn-submitPost btn-newBack" style="background-color:darkgreen">Create</button>

	<input asp-for="CategoryId" type="hidden" />
</form>

Web/PokerStrategy.Web/Views/ForumThread/Thread.cshtml
@model PokerStrategy.Web.ViewModels.Forum.ThreadViewModel
<head>
	<link rel="stylesheet" type="text/css" href="~/css/site.css" />
	@{ViewBag.Title = Model.Title; }
</head>
<div class="container body-content" id="top">

	<!--Thread Title-->
	<h2 style="text-align:left;">
		<b>@Model.Title</b>
	</h2>

	<!--EDIT AND DELETE-->
	@if (this.User.IsInRole("Admin") || this.User.IsInRole("Moderator"))
	{
		<form method="post">
			<!--Delete with Confirmation-->
			<span id="confirmDeleteSpan_@Model.Id" style="display:none">
				<span>Are you sure?</span>
				<button type="submit" class="btn btn-danger" asp-area="Administration" asp-controller="Admin" asp-action="DeleteThreadById" asp-route-id="@Model.Id">Yes</button>
				<a class="btn btn-primary"
				   onclick="confirmDelete('@Model.Id', false)">No</a>
			</span>
			<span id="deleteSpan_@Model.Id">
				<a class="btn btn-danger"
				   onclick="confirmDelete('@Model.Id', true)">Delete</a>
			</span>
		</form>
		<script>
			function confirmDelete(uniqueId, isDeleteClicked) {
				var deleteSpan = 'deleteSpan_' + uniqueId;
				var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

				if (isDeleteClicked) {
					$('#' + deleteSpan).hide();
					$('#' + confirmDeleteSpan).show();
				} else {
					$('#' + deleteSpan).show();
					$('#' + confirmDeleteSpan).hide();
				}
			}
		</script>
	}

	<br />

	<a href="@Model.GetReplyJumpPosition()" class="btn btn-newReply" style="float: left; margin-left:-15px;  background-color: gray; color: white;">Jump to First</a>

	@if (Context.User.Identity.IsAuthenticated)
	{
		<div id="replyRow">
			<span><a asp-controller="ForumReply" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-newReply" style="background-color:darkgreen; color: white; margin-left:5px;">Reply</a></span>
		</div>
	}
</div>

@{string margin = "47px";}
@if (Context.User.Identity.IsAuthenticated)
{
	margin = "0px";
}

<div class="repliesSection" style="margin-top:@margin; margin-bottom: 9px;">
	<!--All Replies-->
	@{int counter = 0;}
	@foreach (var reply in Model.Replies)
	{
		var replyNumber = Model.Replies.Count() - counter;
		counter++;
	<div class="row replyContent replyStyle col-lg-12">
		
		<div class="col-md-2 replyAuthorContainer" id="@reply.Id">
			<b>#@replyNumber</b>
			<div class="bg-cover"
				 style="background-image: url('@reply.PostedByAvatarUrl'); ">
			</div>

			<a>
				<strong class="float-left">@reply.PostedByName</strong>
			</a>  <br />
			<span class="float-left">
			@reply.RepliedOn.ToString("dd-MMM-yyy HH:mm")
			</span>
		</div>
		<div class="col-md-9 replyContentContainer" style="padding:2%">
			<div class="postContent" style="word-break:break-word">
				<!--class="postContent"-->

				@Html.Raw(reply.Content)
			</div>
		</div>

		<div class="replyDeleteBtnContainer" style="margin:1%">
			<!--EDIT AND DELETE-->
			@if (this.User.IsInRole("Admin") || this.User.IsInRole("Moderator"))
			{
				<form method="post">
					<!--Delete with Confirmation-->
					<span id="confirmDeleteReplySpan_@reply.Id" style="display:none">
						<span>Are you sure?</span>
						<button type="submit" class="btn btn-danger"
								asp-area="Administration"
								asp-controller="Admin"
								asp-action="DeleteReplyById"
								asp-route-id="@reply.Id">
							Yes
						</button>
						<a class="btn btn-primary"
						   onclick="confirmDeleteReply('@reply.Id', false)">No</a>
					</span>
					<span id="deleteReplySpan_@reply.Id">
						<a class="btn btn-danger"
						   onclick="confirmDeleteReply('@reply.Id', true)">Delete</a>
					</span>
				</form>
				<script>
					function confirmDeleteReply(uniqueId, isDeleteClicked) {
						var deleteReplySpan = 'deleteReplySpan_' + uniqueId;
						var confirmDeleteReplySpan = 'confirmDeleteReplySpan_' + uniqueId;

						if (isDeleteClicked) {
							$('#' + deleteReplySpan).hide();
							$('#' + confirmDeleteReplySpan).show();
						} else {
							$('#' + deleteReplySpan).show();
							$('#' + confirmDeleteReplySpan).hide();
						}
					}
				</script>
			}

			<!--------Edit reply---------->
			@if (reply.CurrentUserIsCreator || User.IsInRole("Admin"))
			{

				<!--Edit-->
				<form method="post" style="margin-top:15%">
					<a asp-controller="ForumReply" asp-action="EditReplyById"
					   asp-route-id="@reply.Id" class="btn btn-primary">Edit</a>
				</form>
			}

		</div>
	</div>
	}
</div>
<a href="#top" class="btn btn-newReply" style="float:left; background-color:gray; color: white;">Jump to Last</a>