Web/PokerStrategy.Web/Controllers/ForumController.cs
namespace PokerStrategy.Web.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;
    using PokerStrategy.Services.Data;
    using PokerStrategy.Web.ViewModels.Forum;

    public class ForumController : Controller
    {
        private readonly IForumCategoryService categoryService;
        private readonly IForumThreadService threadService;

        public ForumController(
            IForumCategoryService categoryService,
            IForumThreadService threadService)
        {
            this.categoryService = categoryService;
            this.threadService = threadService;
        }

        public IActionResult Index()
        {
            var allForumCategories = this.categoryService
                .GetAll()
                .Select(c => new CategoryViewModel
                {
                    Id = c.Id,
                    Title = c.Title,
                    Description = c.Description,
                });

            CategoriesListingViewModel model = new CategoriesListingViewModel
            {
                CategoriesList = allForumCategories,
            };

            return this.View(model);
        }

        public IActionResult Category(int id)
        {
            var category = this.categoryService.GetById(id);

            var categoryListing = new CategoryViewModel
            {
                Id = category.Id,
                Title = category.Title,
                Description = category.Description,
            };

            var threads = this.threadService
                .GetThreads(category)
                .OrderByDescending(t => t.CreatedOn)
                .ToList();

            var threadListing = threads.Select(t => new ThreadViewModel
            {
                Id = t.Id,
                Title = t.Title,
                InputContent = t.Content,
                CreatedOn = t.CreatedOn,
                PostedByAvatarUrl = t.PostedBy.ImageUrl,
                PostedByName = t.PostedBy.DisplayName,
            })
            .OrderByDescending(t => t.CreatedOn);

            var model = new ThreadListingViewModel
            {
                Category = categoryListing,
                ThreadsList = threadListing,
            };

            return this.View(model);
        }
    }
}

Web/PokerStrategy.Web/Views/Forum/Category.cshtml
@model PokerStrategy.Web.ViewModels.Forum.ThreadListingViewModel
@using PokerStrategy.Common
@using PokerStrategy.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<head>
	<link rel="stylesheet" type="text/css" href="~/css/site.css" />
	@{ViewBag.Title = Model.Category.Title; }
</head>

<center>
	<h1>Discussion Board</h1>
	<h1>@Model.Category.Title</h1>
</center>
<br />

<a type="button" class="btn btn-primary" style="background-color:darkgreen; border:unset; margin-bottom: 10px;" asp-controller="ForumThread" asp-action="Create" asp-route-id="@Model.Category.Id">Open new thread</a>



@if (Model.ThreadsList.Any())
{
	<table class="table table-bordered  table-custom">
		<tbody>
			@foreach (var thread in Model.ThreadsList)
			{
				<tr>
					<td>
						<a asp-controller="ForumThread"
						   asp-action="Thread"
						   asp-route-id="@thread.Id">
							@thread.Title
						</a>
					</td>
					<td>
						@thread.PostedByName
					</td>
					<td>
						@thread.CreatedOn
					</td>


					@if (this.User.IsInRole(GlobalConstants.AdminRoleName))
					{
						<td>
					

							<!--EDIT AND DELETE-->
							@if (this.User.IsInRole("Admin") || this.User.IsInRole("Moderator"))
							{
								<form method="post">
									<!--Delete with Confirmation-->
									<span id="confirmDeleteSpan_@thread.Id" style="display:none">
										<span>Are you sure?</span>
										<button type="submit" class="btn btn-danger" asp-area="Administration" asp-controller="Admin" asp-action="DeleteThreadById" asp-route-id="@thread.Id">Yes</button>
										<a class="btn btn-primary"
										   onclick="confirmDelete('@thread.Id', false)">No</a>
									</span>
									<span id="deleteSpan_@thread.Id">
										<a class="btn btn-danger"
										   onclick="confirmDelete('@thread.Id', true)">Delete</a>
									</span>
								</form>
								<script>
									function confirmDelete(uniqueId, isDeleteClicked) {
										var deleteSpan = 'deleteSpan_' + uniqueId;
										var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

										if (isDeleteClicked) {
											$('#' + deleteSpan).hide();
											$('#' + confirmDeleteSpan).show();
										} else {
											$('#' + deleteSpan).show();
											$('#' + confirmDeleteSpan).hide();
										}
									}
								</script>
							}
						</td>
					}

				</tr>
			}
		</tbody>
	</table>
}
else
{
	<center>
		<h2>No threads in this Board yet.</h2>
	</center>
}

Web/PokerStrategy.Web/Views/Forum/Index.cshtml
@model PokerStrategy.Web.ViewModels.Forum.CategoriesListingViewModel
<head>
	<link rel="stylesheet" type="text/css" href="~/css/site.css" />
	@{ViewBag.Title = "Forum Categories";}
</head>
<h1>Forum Categories</h1>
<br/>
<table class= "table table-hover table-custom border" id="forumIndexTable">
	<tbody>
		@foreach (var cat in Model.CategoriesList)
		{
		<tr>
			<td>
				<a asp-controller="Forum"
				   asp-action="Category"
				   asp-route-id="@cat.Id">
					<b>@cat.Title</b>
				</a>
			</td>
			<td style="text-align: left;">
				@cat.Description
			</td>
		</tr>
		}
	</tbody>
</table>